HELLO = 'HELLO PILLY :)'
WIFI_ATTEMPTS = 40

MOTOR_DELAY = 0 #global > for motors - on top or delays for relays
DEBUG = True
LOG = True

# btns
DEBOUNCE_MS = 20
WAIT_BETWEEN_PRESSED_MS = 500

ON_START_RETURN00 = False

TIME_GO_DOWN_RIGHT = 1
TIME_GO_DOWN_LEFT = 1
TIME_WAIT_BETWEEN_STEPS = 1
TIME_FINISH = 1
TIME_READY = 0.1
TIME_HORIZONTAL_DELAY_ON_RETURN = 1
TIME_CANCELLING = 10

# main motor 
TIME_WAIT_MAIN_ON = 1
TIME_WAIT_MAIN_OFF = 1

TIME_WAIT_LEFT_ON = 0.1
TIME_WAIT_LEFT_OFF = 0
TIME_WAIT_RIGHT_ON = 0.1
TIME_WAIT_RIGHT_OFF = 0

TIME_WAIT_UP_ON = 0.1
TIME_WAIT_UP_OFF = 0
TIME_WAIT_DOWN_ON = 0.1
TIME_WAIT_DOWN_OFF = 0

DUST = False
SLEEP = 1 # main loop