HELLO = 'HELLO PILLY :)'
WIFI_ATTEMPTS = 40

MOTOR_DELAY = 0 #global > for motors - on top or delays for relays
DEBUG = True

# btns
DEBOUNCE_MS = 20
WAIT_BETWEEN_PRESSED_MS = 1000

ON_START_RETURN00 = False

TIME_GO_DOWN_RIGHT = 5
TIME_GO_DOWN_LEFT = 5
TIME_WAIT_BETWEEN_STEPS = 1
TIME_FINISH = 5
TIME_READY = 0.5
TIME_HORIZONTAL_DELAY_ON_RETURN = 5
TIME_CANCELLING = 10

# main motor 
TIME_WAIT_MAIN_ON = 1
TIME_WAIT_MAIN_OFF = 1

# horizontal moror (direction, go)
TIME_WAIT_HDIR_ON = 0
TIME_WAIT_HDIR_OFF = 0
TIME_WAIT_HGO_ON = 0.1
TIME_WAIT_HGO_OFF = 0.1

# vertical motor (direction, go)
TIME_WAIT_VDIR_ON = 0
TIME_WAIT_VDIR_OFF = 0
TIME_WAIT_VGO_ON = 0.1
TIME_WAIT_VGO_OFF = 0.1

DUST = False
SLEEP = 1 # main loop